### ISSUE TITLE
 [vue-i18n-filter] show 'console.warn' in vendor.js

### ISSUE THREAD

**Issue by StangDev** [chiaweilee/vue-i18n-filter#5]
`[vue-i18n-filter] filter 't' already exists.
[vue-i18n-filter] filter 'tc' already exists.
[vue-i18n-filter] filter 'te' already exists.`

how to config?

**Comment by andersbc** [comment]
I have the same problem. The console shows a long list of these warnings. I'm using **[Vuetify](https://vuetifyjs.com/en/components/buttons)** if that makes any difference.. Strangely I have narrowed it down to using two or more vuetify `<v-btn><v-btn>` subcomponents in a component. E.g:

No console warning:
```html
<v-btn>hello<v-btn>
```

Warnings:
```html
<v-btn>hello a<v-btn>
<v-btn>hello b<v-btn>
```
